export const CategoryListActions = {
  LOAD_CATEGORIES_IN_PROGRESS: "LOAD_CATEGORIES_IN_PROGRESS",
  LOAD_CATEGORIES_SUCESS: "LOAD_CATEGORIES_SUCESS",
  LOAD_CATEGORIES_ERROR: "LOAD_CATEGORIES_ERROR",
};
