export const Actions = {
  IN_PROGRESS: "IN_PROGRESS",
  ERROR: "ERROR",
  LOAD_CATEGORIES_SUCESS: "LOAD_CATEGORIES_SUCESS",
  LOAD_TOPICS_SUCESS: "LOAD_TOPICS_SUCESS",
  LOAD_POSTS_SUCESS: "LOAD_POSTS_SUCESS",
};
